=== Sponken/clover-cooked/application/data/schemas/recipe_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Recipe",
  "description": "Representation of a recipe",
  "type": "object",
  "required": [
    "name",
    "description",
    "ingredients",
    "resources",
    "tasks",
    "taskDependencies",
    "portions"
  ],
  "properties": {
    "name": {
      "description": "The name of the meal",
      "type": "string"
    },
    "description": {
      "description": "A short description of the meal, recipe and your life or whatever",
      "type": "string"
    },
    "portions": {
      "description": "The number of portions the recipe is meant for.",
      "type": "integer"
    },
    "ingredients": {
      "description": "The ingredients needed for this recipe",
      "type": "array",
      "items": {
        "description": "An ingredient",
        "type": "object",
        "properties": {
          "id": { "type": "string", "$id": "#ingredientId" },
          "name": { "type": "string" },
          "unit": { "type": "string" }
        },
        "required": ["id", "name", "unit"]
      }
    },
    "resources": {
      "description": "The resources needed for this recipe",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": { "type": "string", "$id": "#resourceId" },
          "name": { "type": "string" },
          "description": { "type": "string" }
        },
        "required": ["id", "name"]
      }
    },

    "tasks": {
      "description": "The tasks/steps performed",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "name", "instructions", "ingredients", "resources"],
        "properties": {
          "id": { "type": "string", "$id": "#taskId" },
          "name": { "type": "string" },
          "instructions": { "type": "string" },
          "passive": { "type": "boolean" },
          "nonInterruptable": { "type": "boolean" },
          "initalTask": { "type": "boolean" },
          "finalTask": { "type": "boolean" },
          "estimatedTime": { "type": "number" },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ingredientId": { "$ref": "#ingredientId" },
                "amount": { "type": "number" }
              },
              "required": ["ingredientId", "amount"]
            }
          },
          "resources": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "resourceId": { "$ref": "#resourceId" },
                "amount": { "type": "number" }
              },
              "required": ["resourceId", "amount"]
            }
          }
        }
      }
    },
    "taskDependencies": {
      "description": "The dependecies of which tasks are to be completed before a given task",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "properties": {
          "taskId": { "$ref": "#taskId" },
          "dependsOn": {
            "type": "array",
            "items": { "$ref": "#taskId" },
            "uniqueItems": true
          },
          "strongDependsOn": {
            "type": "array",
            "items": { "$ref": "#taskId" },
            "uniqueItems": true
          }
        },
        "required": ["taskId"],
        "anyOf": [
          { "required": ["dependsOn"] },
          { "required": ["strongDependsOn"] }
        ]
      }
    }
  }
}

=== Sponken/clover-cooked/application/data/recipes/gräddtråtra.json
{
  "name": "Gräddtårta",
  "description": "A simple template for creating a recipe",
  "portions": 1,
  "ingredients": [{ "id": "id", "name": "name", "unit": "st" }],
  "resources": [{ "id": "ugn", "name": "Ugn" }],
  "tasks": [
    {
      "id": "id",
      "name": "name",
      "instructions": "instructions",
      "passive": false,
      "nonInterruptable": false,
      "initalTask": false,
      "finalTask": false,
      "estimatedTime": 999,
      "ingredients": [{ "ingredientId": "id", "amount": 99 }],
      "resources": [{ "resourceId": "resource", "amount": 99 }]
    },
    {
      "id": "ugnPå",
      "name": "Sätt på ugnen",
      "instructions": "Sätt på ugnen på 175°C.",
      "initalTask": true,
      "estimatedTime": 1,
      "ingredients": [],
      "resources": [{ "resourceId": "ugn", "amount": 1 }]
    }
  ],
  "taskDependencies": [
    {
      "taskId": "id",
      "dependsOn": ["otherID"],
      "strongDependsOn": ["thirdID"]
    }
  ]
}

=== Sponken/clover-cooked/application/data/recipe_templates/recipe_template.json
{
  "name": "template",
  "description": "A simple template for creating a recipe",
  "portions": 1,
  "ingredients": [{ "id": "ingredient", "name": "name", "unit": "st" }],
  "resources": [{ "id": "resource", "name": "name" }],
  "tasks": [
    {
      "id": "id",
      "name": "name",
      "instructions": "instructions",
      "passive": false,
      "nonInterruptable": false,
      "initalTask": false,
      "finalTask": true,
      "estimatedTime": 999,
      "ingredients": [{ "ingredientId": "ingredient", "amount": 99 }],
      "resources": [{ "resourceId": "resource", "amount": 99 }]
    },
    {
      "id": "otherID",
      "name": "otherName",
      "instructions": "More instructions",
      "estimatedTime": 999,
      "ingredients": [{ "ingredientId": "ingredient", "amount": 99 }],
      "resources": [{ "resourceId": "resource", "amount": 99 }]
    }
  ],
  "taskDependencies": [
    {
      "taskId": "id",
      "dependsOn": ["otherID"],
      "strongDependsOn": ["thirdID"]
    }
  ]
}
